name: dart_frog_shared
description: Share code for dart_frog projects
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  dio: ^5.4.1
  dart_frog: ^1.1.0
  logging: ^1.2.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  lint: ^2.3.0
