name: dart_frog_shared
description: Shared exception handling, logging, and middleware utilities for Dart Frog server projects
version: 2.2.1
repository: https://github.com/tripomatic/dart_frog_shared
homepage: https://github.com/tripomatic/dart_frog_shared

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  dio: ^5.9.0
  dart_frog: ^1.2.2
  dart_firebase_admin: ^0.4.1
  logging: ^1.3.0
  shelf: ^1.4.1
  shelf_limiter: ^2.0.0
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.26.3
  lint: ^2.8.0
