name: dart_frog_shared
description: Shared code for all dart_frog projects with helpful libraries
version: 1.8.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  dio: ^5.9.0
  dart_frog: ^1.2.2
  dart_firebase_admin: ^0.4.1
  logging: ^1.3.0
  shelf: ^1.4.1
  shelf_limiter: ^2.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.26.3
  lint: ^2.8.0
